### ISSUE TITLE
User flow on device pages should be clearer

### ISSUE THREAD

**Issue by autonome** [mozilla/feedthefox#207]
Currently the device pages have a link to a build (or a website with a build), and a button (?!) for documentation.
- It's not clear when the download link is a large file or a link to a page that should have a large file.
- It's not clear what to do with the build when you do download it. The [documentation] link isn't clearly the next step.

We should improve the pages for official builds to be steps, eg:
1. Download the build [file size noted]
2. Read the [documentation] to install the build

For community builds we should have text that clearly says that the download is on the community page and that the documentation should also be there.

**Comment by brianking** [comment]
+1 to this. I would also distinguish further the button between Mozilla maintained builds and community builds. Right now it is the text that differes, but I would make them different colours.

**Comment by gaby2300** [comment]
Flame builds are community maintained ones. They are excellent but cannot be updated on the nightly-test channel due to the following bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1214737 (please take a look at the attachment image, it's the issue I have)
Dogfood builds for Flame don´t seem to be available, will this be fixed soon?

**Comment by comzeradd** [comment]
So we distinguish builds based on:
1. Mozilla or Community maintained
2. Direct or external link
3. Foxfooding or not builds

For the documentation does this mean the link should be build specific?

**Comment by comzeradd** [comment]
@gaby2300 Is your question related on this issue? It seems you seek updates around the Foxfooding program, so [Discourse](https://discourse.mozilla-community.org/c/firefox-os-participation) is a better place to ask.

**Comment by gaby2300** [comment]
@comzeradd I made my comment here because you were trying to distinguish different kind of builds and asking if it meant the link should be build specific, that´s why I commented about the Flame builds being community maintained. 
I will ask in Discourse then, thanks!

**Comment by brianking** [comment]
@comzeradd for documentation what we have right now is:
- For Mozilla builds we create a page here: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Phone_guide
- For community builds there may or may not be documentation separate to just a page with the link of the build. If we can find a page, we link to it. Otherwise we like to the same page as the build

**Comment by brianking** [comment]
20151202 Triage - P1.

**Comment by brianking** [comment]
Since we are removing FxOS features, this is no longer relevant. Reopen if you think it still is.
